---
# handlers file for prometheus
- name: prometheus reenable
  command: systemctl reenable prometheus.service

- name: restart prometheus
  service:
    name: prometheus
    state: restarted

- name: reload prometheus
  service:
    name: prometheus
    state: reloaded

- name: alertmanager reenable
  command: systemctl reenable prometheus.service

- name: restart alertmanager
  service:
    name: alertmanager
    state: restarted

- name: reload alertmanager
  service:
    name: alertmanager
    state: reloaded